
services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: haslo123
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  database:
